name = "TestMIDI"
uuid = "dd1520e7-34ca-4094-899e-a4bd33e599c0"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]
version = "0.1.0"

[deps]
MIDI = "f57c4921-e30c-5f49-b073-3f2f2ada663e"

# examples
# MusicVisualizations = "8e838768-4b4f-4130-9d6d-43f7b35ca0d6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"

[targets]
test = ["Test", "Jive"]

[compat]
julia = "1"
